language: php
php:
  - 5.6

script:
  - phpize
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-q --show-diff" make test
  
notifications:
  email: jz@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
